# Generated by Django 4.2.24 on 2025-09-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'อาหาร'), ('transport', 'เดินทาง'), ('entertainment', 'บันเทิง'), ('shopping', 'ช้อปปิ้ง'), ('health', 'สุขภาพ'), ('other', 'อื่นๆ')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
