# Generated by Django 4.2.24 on 2025-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('อาหาร', 'อาหาร'), ('เครื่องดื่ม', 'เครื่องดื่ม'), ('เดินทาง', 'เดินทาง'), ('ที่พัก', 'ที่พัก'), ('ช้อปปิ้ง', 'ช้อปปิ้ง'), ('อื่นๆ', 'อื่นๆ')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
